[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 0.9

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14.0

[colors]
primary = { background = "#1e1e2e", foreground = "#cdd6f4" }

normal = { black   = "#1e1e2e", red     = "#f38ba8", green   = "#a6e3a1", yellow  = "#f9e2af", blue    = "#89b4fa", magenta = "#f5c2e7", cyan    = "#94e2d5", white   = "#bac2de" }

bright = { black   = "#585b70", red     = "#f38ba8", green   = "#a6e3a1", yellow  = "#f9e2af", blue    = "#89b4fa", magenta = "#f5c2e7", cyan    = "#94e2d5", white   = "#a6adc8" }
